
language: node_js
node_js:
  - "12"
sudo: true
 
branches:
  only:
  - master
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key: $TOKEN
  app: digich-test
