
language: node_js
node_js:
  - "12"
sudo: true
 
branches:
  only:
  - master
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key: b8d64276-08e4-4071-8a5c-df608feebe34
  app: digich-test
